server:
  port: 8010

spring:
  application:
    name: bookmark-service
  data:
     mongodb:
        host: 172.16.12.27
        prot: 27017
        database: springcloud

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
